// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview This file defines a Genkit flow for providing code review suggestions using AI.
 *
 * - codeReviewSuggestions - A function that takes code as input and returns AI-powered suggestions for improvements, bug detection, and vulnerability identification.
 * - CodeReviewSuggestionsInput - The input type for the codeReviewSuggestions function.
 * - CodeReviewSuggestionsOutput - The return type for the codeReviewSuggestions function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const CodeReviewSuggestionsInputSchema = z.object({
  code: z.string().describe('The code snippet to be reviewed.'),
  language: z.string().describe('The programming language of the code snippet (e.g., Python, JavaScript, Java).'),
});
export type CodeReviewSuggestionsInput = z.infer<typeof CodeReviewSuggestionsInputSchema>;

const CodeReviewSuggestionsOutputSchema = z.object({
  suggestions: z.array(z.string()).describe('An array of AI-powered suggestions for code improvements, bug detection, and vulnerability identification.'),
});
export type CodeReviewSuggestionsOutput = z.infer<typeof CodeReviewSuggestionsOutputSchema>;

export async function codeReviewSuggestions(input: CodeReviewSuggestionsInput): Promise<CodeReviewSuggestionsOutput> {
  return codeReviewSuggestionsFlow(input);
}

const codeReviewSuggestionsPrompt = ai.definePrompt({
  name: 'codeReviewSuggestionsPrompt',
  input: {schema: CodeReviewSuggestionsInputSchema},
  output: {schema: CodeReviewSuggestionsOutputSchema},
  prompt: `You are an AI-powered code review tool. You will receive a code snippet and provide suggestions for improvements, bug detection, and vulnerability identification.

  Programming Language: {{{language}}}

  Code Snippet:
  \`\`\`{{{language}}}
  {{{code}}}
  \`\`\`

  Suggestions (provide as a numbered list):
  `,
});

const codeReviewSuggestionsFlow = ai.defineFlow({
  name: 'codeReviewSuggestionsFlow',
  inputSchema: CodeReviewSuggestionsInputSchema,
  outputSchema: CodeReviewSuggestionsOutputSchema,
}, async (input) => {
  const {output} = await codeReviewSuggestionsPrompt(input);
  return output!;
});
